global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'edt-app'

    scrape_interval: 5s

    metrics_path: '/prometheus'

    static_configs:
      - targets: [ 'localhost:9091' ]