apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  datasource_user: {{ .Values.spring.datasource_user | b64enc }}
  datasource_pass: {{ .Values.spring.datasource_pass | b64enc }}
  datasource_url: {{ .Values.spring.datasource_url | b64enc }}
  redis_host: {{ .Values.spring.redis_host | b64enc }}
  redis_port: {{ .Values.spring.redis_port | b64enc }}
  redis_password: {{ .Values.spring.redis_password | b64enc }}