apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edt-app.fullname" . }}
  labels:
    {{- include "edt-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "edt-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "edt-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edt-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.postgresql.enabled }}
            - name: SPRING_PROFILE
              value: "prod"
            - name: DB_HOST
              value: "{{ .Release.Name}}-postgresql-headless"
            - name: DB_NAME
              value: {{ .Values.postgresql.global.postgresql.postgresqlDatabase | quote }}
            - name: MASTER_PASSWORD
              value: {{ .Values.postgresql.global.postgresql.postgresqlPassword | quote }}
            - name: MASTER_USERNAME
              value: {{ .Values.postgresql.global.postgresql.postgresqlUsername | quote }}
            - name: DB_PORT
              value: {{ .Values.postgresql.global.postgresql.servicePort | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.image.livenessUrl }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.image.livenessUrl }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}