name: Check Out, Build and Push Image to DockerHub

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker:
    name: Log-in, build and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU Action
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Build Action
        uses: docker/setup-buildx-action@v1
      -
        name: Log-in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
      -
        name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: partaloski/expirydatetracker-api:latest